"""Migration auto-generated at 2022-02-13 17:36:55.607001.

Revision ID: c05835d8ab3f
Revises: None
Create Date: 2022-02-13 17:36:55.648655

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c05835d8ab3f"
down_revision = None


def upgrade():
    schema_upgrades()


def downgrade():
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopping_list",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shopping_list_uid"), "shopping_list", ["uid"], unique=True)
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shopping_list_uid"), table_name="shopping_list")
    op.drop_table("shopping_list")
    # ### end Alembic commands ###
