"""02_add_item.

Revision ID: a25e45696c9c
Revises: 6dc7c5f55dce
Create Date: 2022-02-12 16:00:46.526217

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a25e45696c9c"
down_revision = "6dc7c5f55dce"


def upgrade():
    schema_upgrades()


def downgrade():
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_checked", sa.Boolean(), nullable=True),
        sa.Column("shopping_list", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shopping_list"],
            ["shopping_list.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_uid"), "item", ["uid"], unique=True)
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_uid"), table_name="item")
    op.drop_table("item")
    # ### end Alembic commands ###
