"""03_cascade_on_delete_shopping_list.

Revision ID: 8d25a0ba7435
Revises: 502a6bfb7d5f
Create Date: 2022-02-14 18:32:08.294632

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8d25a0ba7435"
down_revision = "502a6bfb7d5f"


def upgrade():
    schema_upgrades()


def downgrade():
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("item_shopping_list_id_fkey", "item", type_="foreignkey")
    op.create_foreign_key(
        None, "item", "shopping_list", ["shopping_list_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "item", type_="foreignkey")
    op.create_foreign_key(
        "item_shopping_list_id_fkey", "item", "shopping_list", ["shopping_list_id"], ["id"]
    )
    # ### end Alembic commands ###
