"""Migration auto-generated at 2022-03-19 18:58:24.102862.

Revision ID: 0ce328f7911a
Revises: 8d25a0ba7435
Create Date: 2022-03-19 18:58:24.482990

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0ce328f7911a"
down_revision = "8d25a0ba7435"


def upgrade():
    schema_upgrades()


def downgrade():
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
        sa.Column("contributor_scopes", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_uid"), "user", ["uid"], unique=True)
    op.add_column("shopping_list", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key("user_id", "shopping_list", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_id", "shopping_list", type_="foreignkey")
    op.drop_column("shopping_list", "user_id")
    op.drop_index(op.f("ix_user_uid"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
