"""Migration auto-generated at 2022-03-25 22:46:33.201275.

Revision ID: cc036cbdd393
Revises: 0ce328f7911a
Create Date: 2022-03-25 22:46:33.420325

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cc036cbdd393"
down_revision = "0ce328f7911a"


def upgrade():
    schema_upgrades()


def downgrade():
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contributor_scopes", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("shopping_list_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shopping_list_id"],
            ["shopping_list.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["shopping_list.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("user", "password")
    op.drop_column("user", "contributor_scopes")
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "contributor_scopes", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True
        ),
    )
    op.add_column("user", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table("user_permissions")
    # ### end Alembic commands ###
