"""Migration auto-generated at 2022-03-27 21:17:39.008679.

Revision ID: 5ecbaf1363d6
Revises: cc036cbdd393
Create Date: 2022-03-27 21:17:39.973769

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "5ecbaf1363d6"
down_revision = "cc036cbdd393"


def upgrade():
    schema_upgrades()


def downgrade():
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_permissions_user_id_fkey", "user_permissions", type_="foreignkey")
    op.create_foreign_key(None, "user_permissions", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_permissions", type_="foreignkey")
    op.create_foreign_key(
        "user_permissions_user_id_fkey", "user_permissions", "shopping_list", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
